# foundry.toml

[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    "@uniswap/v4-core/=lib/v4-core/",
    "forge-gas-snapshot=lib/v4-core/lib/forge-gas-snapshot/src/",
    "forge-std=lib/v4-core/lib/forge-std/src/",
    "permit2=lib/v4-periphery/lib/permit2/",
    "solmate=lib/v4-core/lib/solmate/",
    "v4-core=lib/v4-core/src/",
    "v4-periphery=lib/v4-periphery/src/",
    "@openzeppelin=lib/openzeppelin-contracts/"
]
solc_version = "0.8.26"
evm_version = "cancun"
ffi = true

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
sepolia = "${SEPOLIA_RPC_URL}"

# Etherscan API Keys for contract verification (optional)
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }